//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.239
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Dieser Quellcode wurde automatisch generiert von xsd, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class plist
{

    private object itemField;

    private ItemChoiceType itemElementNameField;

    private string versionField;

    public plist()
    {
        this.versionField = "1.0";
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("array", typeof(array))]
    [System.Xml.Serialization.XmlElementAttribute("data", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("date", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("dict", typeof(dict))]
    [System.Xml.Serialization.XmlElementAttribute("false", typeof(@false))]
    [System.Xml.Serialization.XmlElementAttribute("integer", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("real", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("string", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("true", typeof(@true))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public object Item
    {
        get
        {
            return this.itemField;
        }
        set
        {
            this.itemField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType ItemElementName
    {
        get
        {
            return this.itemElementNameField;
        }
        set
        {
            this.itemElementNameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("1.0")]
    public string version
    {
        get
        {
            return this.versionField;
        }
        set
        {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class array
{

    private object[] itemsField;

    private ItemsChoiceType1[] itemsElementNameField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("array", typeof(array))]
    [System.Xml.Serialization.XmlElementAttribute("data", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("date", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("dict", typeof(dict))]
    [System.Xml.Serialization.XmlElementAttribute("false", typeof(@false))]
    [System.Xml.Serialization.XmlElementAttribute("integer", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("real", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("string", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("true", typeof(@true))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items
    {
        get
        {
            return this.itemsField;
        }
        set
        {
            this.itemsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType1[] ItemsElementName
    {
        get
        {
            return this.itemsElementNameField;
        }
        set
        {
            this.itemsElementNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class dict
{

    private string[] keyField;

    private object[] itemsField;

    private ItemsChoiceType[] itemsElementNameField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("key")]
    public string[] key
    {
        get
        {
            return this.keyField;
        }
        set
        {
            this.keyField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("array", typeof(array))]
    [System.Xml.Serialization.XmlElementAttribute("data", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("date", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("dict", typeof(dict))]
    [System.Xml.Serialization.XmlElementAttribute("false", typeof(@false))]
    [System.Xml.Serialization.XmlElementAttribute("integer", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("real", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("string", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("true", typeof(@true))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items
    {
        get
        {
            return this.itemsField;
        }
        set
        {
            this.itemsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType[] ItemsElementName
    {
        get
        {
            return this.itemsElementNameField;
        }
        set
        {
            this.itemsElementNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class @false
{
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class @true
{
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "", IncludeInSchema = false)]
public enum ItemsChoiceType
{

    /// <remarks/>
    array,

    /// <remarks/>
    data,

    /// <remarks/>
    date,

    /// <remarks/>
    dict,

    /// <remarks/>
    @false,

    /// <remarks/>
    integer,

    /// <remarks/>
    real,

    /// <remarks/>
    @string,

    /// <remarks/>
    @true,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "", IncludeInSchema = false)]
public enum ItemsChoiceType1
{

    /// <remarks/>
    array,

    /// <remarks/>
    data,

    /// <remarks/>
    date,

    /// <remarks/>
    dict,

    /// <remarks/>
    @false,

    /// <remarks/>
    integer,

    /// <remarks/>
    real,

    /// <remarks/>
    @string,

    /// <remarks/>
    @true,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "", IncludeInSchema = false)]
public enum ItemChoiceType
{

    /// <remarks/>
    array,

    /// <remarks/>
    data,

    /// <remarks/>
    date,

    /// <remarks/>
    dict,

    /// <remarks/>
    @false,

    /// <remarks/>
    integer,

    /// <remarks/>
    real,

    /// <remarks/>
    @string,

    /// <remarks/>
    @true,
}
